export const FETCH_PRODUCTS = "FETCH_PRODUCTS";
export const FILTER_PRODUCTS_BY_SIZE = "FILTER_PRODUCTS_BY_SIZE";
export const FILTER_PRODUCTS_BY_CATEGORY = "FILTER_PRODUCTS_BY_CATEGORY";
export const FILTER_PRODUCTS_BY_GENDER = "FILTER_PRODUCTS_BY_GENDER";
export const FILTER_PRODUCTS_BY_SEARCH = "FILTER_PRODUCTS_BY_SEARCH";

export const PRODUCT_ADD_REQUEST = 'PRODUCT_ADD_REQUEST';
export const PRODUCT_ADD_SUCCESS = 'PRODUCT_ADD_SUCCESS';
export const PRODUCT_ADD_FAIL = 'PRODUCT_ADD_FAIL';

export const FETCH_DETAILS_PRODUCTS = 'FETCH_DETAILS_PRODUCTS';
export const FETCH_DETAILS_FAIL = 'FETCH_DETAILS_FAIL';
export const FETCH_DETAILS_RESET = 'FETCH_DETAILS_RESET';

export const ORDER_PRODUCTS_BY_PRICE = "ORDER_PRODUCTS_BY_PRICE";

export const FETCH_SIZE_PRODUCTS = 'FETCH_SIZE_PRODUCTS';
export const FETCH_SIZE_RESET = "FETCH_SIZE_RESET";

export const FETCH_REQUEST = 'FETCH_REQUEST';
export const FETCH_FAIL = 'FETCH_FAIL';
export const FETCH_RESET = 'FETCH_RESET';

export const UPDATE_PRODUCT_REQUEST = 'UPDATE_PRODUCT_REQUEST';
export const UPDATE_PRODUCT_SUCCESS = 'UPDATE_PRODUCT_SUCCESS';
export const UPDATE_PRODUCT_FAIL = 'UPDATE_PRODUCT_FAIL';

export const DELETE_PRODUCT_REQUEST = 'DELETE_PRODUCT_REQUEST';
export const DELETE_PRODUCT_SUCCESS = 'DELETE_PRODUCT_SUCCESS';
export const DELETE_PRODUCT_FAIL = 'DELETE_PRODUCT_FAIL';
